const fs = require("fs");
const path = require("path");

// --- layout.tsx ---
const layout = [
  'import type { Metadata } from "next";',
  'import { Inter, Newsreader, Space_Mono } from "next/font/google";',
  'import "./globals.css";',
  '',
  'const inter = Inter({ variable: "--font-inter", subsets: ["latin"], display: "swap" });',
  'const newsreader = Newsreader({ variable: "--font-newsreader", subsets: ["latin"], display: "swap" });',
  'const spaceMono = Space_Mono({ weight: ["400", "700"], variable: "--font-space-mono", subsets: ["latin"], display: "swap" });',
  '',
  'export const metadata: Metadata = {',
  '  metadataBase: new URL("https://sangwajesly.vercel.app"),',
  '  title: {',
  '    template: "%s | Sangwa Jesly",',
  '    default: "Sangwa Jesly | Brand Designer & Web Developer in Bamenda, Cameroon",',
  '  },',
  '  description: "I design brands, build websites, and create event and social media graphics for small businesses and startups in Cameroon and beyond.",',
  '  openGraph: {',
  '    title: "Sangwa Jesly | Brand Designer & Web Developer in Bamenda, Cameroon",',
  '    description: "I design brands, build websites, and create event and social media graphics for small businesses and startups in Cameroon and beyond.",',
  '    url: "https://sangwajesly.vercel.app",',
  '    siteName: "Sangwa Jesly",',
  '    images: [{ url: "/brand/og-default.jpg", width: 1200, height: 630 }],',
  '    locale: "en_US",',
  '    type: "website",',
  '  },',
  '  twitter: { card: "summary_large_image" },',
  '  robots: { index: true, follow: true },',
  '};',
  '',
  'export default function RootLayout({ children }: { children: React.ReactNode }) {',
  '  return (',
  '    <html lang="en" className={`${inter.variable} ${newsreader.variable} ${spaceMono.variable}`}>',
  '      <body className="min-h-screen bg-bg text-fg font-sans antialiased">',
  '        <a href="#main" className="skip-link">Skip to content</a>',
  '        {children}',
  '      </body>',
  '    </html>',
  '  );',
  '}',
].join("\n");
fs.writeFileSync(path.join(__dirname, "src/app/layout.tsx"), layout);

// --- page.tsx (home) ---
const home = [
  'import Link from "next/link";',
  'import { Palette, Monitor, Image } from "lucide-react";',
  'import { projects, categoryGroups } from "@/content/projects";',
  'import { siteConfig } from "@/lib/config";',
  'import { Header } from "@/components/Header";',
  'import { Footer } from "@/components/Footer";',
  'import { FAQAccordion } from "@/components/FAQAccordion";',
  'import { StickyMobileCTA } from "@/components/StickyMobileCTA";',
  '',
  'export default function Home() {',
  '  const services = [',
  '    { icon: "palette", title: "Brand identity", text: "A logo and a clear visual style, so your business looks professional and consistent everywhere: signs, social media and documents." },',
  '    { icon: "monitor", title: "Websites", text: "A simple, fast website that works well on phones and makes it easy for customers to find you and get in touch." },',
  '    { icon: "image", title: "Event and social media designs", text: "Flyers, banners, badges and posts that catch attention and tell people what to do next." },',
  '  ];',
  '  const steps = [',
  '    { n: "01", title: "We talk", text: "You tell me about your business and what you need." },',
  '    { n: "02", title: "I make a plan", text: "I explain what I\\u2019ll make, how long it will take and what it will cost, before we start." },',
  '    { n: "03", title: "I design and build", text: "You see progress along the way and can ask for changes." },',
  '    { n: "04", title: "I deliver and support", text: "You get all your final files. I stay available if you need help afterwards." },',
  '  ];',
  '  const marqueeItems = ["Brand design", "Websites", "Event branding", "Flyers", "Social media", "Logos", "Icons"];',
  '',
  '  return (',
  '    <>',
  '      <Header />',
  '      <main id="main">',
  '',
  '        {/* 8.2 Hero */}',
  '        <section id="hero" className="py-20 md:py-32 px-6 md:px-10">',
  '          <div className="max-w-[1200px] mx-auto flex flex-col-reverse md:flex-row gap-12 items-center">',
  '            <div className="flex-1 flex flex-col gap-6">',
  '              <h1 style={{ fontSize: "clamp(2.5rem, 6vw, 5rem)" }} className="font-serif font-bold leading-[1.05] tracking-tight">',
  '                I design and build the brand, website and graphics your business needs to get noticed.',
  '              </h1>',
  '              <p className="text-lg md:text-xl text-muted leading-relaxed max-w-2xl">',
  '                I&apos;m Jesly, a designer and web developer in Bamenda, Cameroon. I help small businesses, startups and community groups look professional and make it easy for customers to reach them.',
  '              </p>',
  '              <div className="flex flex-wrap gap-3 font-mono text-xs uppercase tracking-widest">',
  '                <span className="bg-surface px-3 py-1.5 rounded-lg border border-border">Brand design</span>',
  '                <span className="bg-surface px-3 py-1.5 rounded-lg border border-border">Websites</span>',
  '                <span className="bg-surface px-3 py-1.5 rounded-lg border border-border">Event &amp; social media designs</span>',
  '              </div>',
  '              <div className="flex flex-col sm:flex-row gap-4 mt-2">',
  '                <a href={siteConfig.whatsappLink} target="_blank" rel="noopener noreferrer" className="bg-accent text-bg px-8 py-4 text-center font-bold rounded-xl hover:opacity-90 transition-opacity min-h-[48px] flex items-center justify-center">Chat with me on WhatsApp</a>',
  '                <Link href="#work" className="border border-border text-fg px-8 py-4 text-center font-medium rounded-xl hover:bg-surface transition-colors min-h-[48px] flex items-center justify-center">See my work</Link>',
  '              </div>',
  '              <p className="text-sm text-muted">I&apos;ve worked with {siteConfig.clients.join(", ")}.</p>',
  '              {siteConfig.replyTime && <p className="text-sm text-muted">I usually reply within <strong>{siteConfig.replyTime}</strong>.</p>}',
  '            </div>',
  '            <div className="flex-1 max-w-xs md:max-w-sm">',
  '              <img src="/brand/portrait.jpg" alt="Sangwa Jesly, designer and web developer" width={480} height={600} className="w-full rounded-2xl grayscale rotate-2 border-4 border-fg/10 hover:grayscale-0 hover:rotate-0 transition-all duration-500" />',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '        {/* Marquee */}',
  '        <div className="overflow-hidden border-y border-border py-4" aria-hidden="true">',
  '          <div className="flex animate-marquee whitespace-nowrap">',
  '            {[...marqueeItems, ...marqueeItems, ...marqueeItems, ...marqueeItems].map((item, i) => (',
  '              <span key={i} className="mx-6 text-2xl md:text-3xl font-serif font-bold text-muted/30">{item} <span className="text-accent/40 mx-4">&bull;</span></span>',
  '            ))}',
  '          </div>',
  '        </div>',
  '',
  '        {/* 8.3 Selected work */}',
  '        <section id="work" className="py-20 md:py-28 px-6 md:px-10 bg-surface/50">',
  '          <div className="max-w-[1200px] mx-auto">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-serif font-bold mb-2">Selected work</h2>',
  '            <p className="text-lg text-muted mb-16">A few projects I&apos;m proud of. Tap any project to see the details.</p>',
  '            <div className="flex flex-col gap-20">',
  '              {categoryGroups.map((group) => {',
  '                const gp = projects.filter((p) => p.categoryGroup === group.id && p.published);',
  '                if (!gp.length) return null;',
  '                return (',
  '                  <div key={group.id}>',
  '                    <div className="flex items-center gap-4 mb-8">',
  '                      <h3 className="text-xl font-bold">{group.title}</h3>',
  '                      <span className="font-mono text-xs text-muted bg-border px-2.5 py-1 rounded-lg">{gp.length}</span>',
  '                    </div>',
  '                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">',
  '                      {gp.map((project) => (',
  '                        <Link href={"/work/" + project.slug} key={project.slug} className="group flex flex-col gap-4 rounded-2xl focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-bg">',
  '                          <div className="aspect-[4/3] bg-surface-raised rounded-2xl overflow-hidden border border-border group-hover:border-accent/40 transition-colors">',
  '                            <img src={project.images.cover} alt={project.title} width={800} height={600} loading="lazy" className="w-full h-full object-cover group-hover:scale-[1.03] transition-transform duration-300" />',
  '                          </div>',
  '                          <div className="flex flex-col gap-1.5">',
  '                            <div className="flex justify-between font-mono text-xs text-muted uppercase tracking-widest">',
  '                              <span>{project.number} &middot; {project.category}</span>',
  '                              {project.year && <span>{project.year}</span>}',
  '                            </div>',
  '                            <h4 className="text-lg font-bold font-serif">{project.title}</h4>',
  '                            <p className="text-muted text-sm line-clamp-2">{project.summary}</p>',
  '                            <span className="text-accent text-sm font-medium mt-2 inline-flex items-center gap-1 group-hover:gap-2 transition-all">View project <span aria-hidden="true">&rarr;</span></span>',
  '                          </div>',
  '                        </Link>',
  '                      ))}',
  '                    </div>',
  '                  </div>',
  '                );',
  '              })}',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.4 Services */}',
  '        <section id="services" className="py-20 md:py-28 px-6 md:px-10">',
  '          <div className="max-w-[1200px] mx-auto">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-serif font-bold mb-12">How I can help</h2>',
  '            <ol className="flex flex-col divide-y divide-border">',
  '              {services.map((s, i) => (',
  '                <li key={s.title} className="py-8 flex flex-col md:flex-row md:items-start gap-4 md:gap-8">',
  '                  <span className="font-mono text-accent text-sm tracking-widest shrink-0">0{i + 1}</span>',
  '                  <div className="flex-1">',
  '                    <h3 className="text-xl font-bold mb-2">{s.title}</h3>',
  '                    <p className="text-muted leading-relaxed max-w-xl">{s.text}</p>',
  '                  </div>',
  '                  <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center text-accent shrink-0">',
  '                    {s.icon === "palette" && <Palette size={24} />}',
  '                    {s.icon === "monitor" && <Monitor size={24} />}',
  '                    {s.icon === "image" && <Image size={24} />}',
  '                  </div>',
  '                </li>',
  '              ))}',
  '            </ol>',
  '            <p className="text-muted text-sm mt-8 max-w-2xl">Also available: simple automations that save you time on repeated tasks, like answering common questions or collecting orders.</p>',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.5 Process */}',
  '        <section className="py-20 md:py-28 px-6 md:px-10 bg-surface/50">',
  '          <div className="max-w-[1200px] mx-auto">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-serif font-bold mb-12">How we&apos;ll work together</h2>',
  '            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">',
  '              {steps.map((s) => (',
  '                <div key={s.n} className="flex flex-col gap-4">',
  '                  <span className="font-mono text-accent text-sm tracking-widest">{s.n}</span>',
  '                  <h3 className="text-xl font-bold">{s.title}</h3>',
  '                  <p className="text-muted leading-relaxed">{s.text}</p>',
  '                </div>',
  '              ))}',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.6 About */}',
  '        <section id="about" className="py-20 md:py-28 px-6 md:px-10">',
  '          <div className="max-w-[1200px] mx-auto flex flex-col md:flex-row gap-12 items-start">',
  '            <div className="flex-1 max-w-xs">',
  '              <img src="/brand/portrait.jpg" alt="Sangwa Jesly" width={400} height={500} className="w-full rounded-2xl" />',
  '            </div>',
  '            <div className="flex-1 max-w-xl">',
  '              <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-serif font-bold mb-6">Hi, I&apos;m Jesly</h2>',
  '              <div className="text-muted text-lg leading-relaxed space-y-4">',
  '                <p>I&apos;m a designer and web developer based in Bamenda, Cameroon. I enjoy helping local businesses and communities look as professional as the big brands.</p>',
  '              </div>',
  '              <div className="flex gap-4 mt-8">',
  '                {siteConfig.github && <a href={siteConfig.github} target="_blank" rel="noopener noreferrer" className="text-muted hover:text-accent transition-colors font-mono text-sm">GitHub &rarr;</a>}',
  '              </div>',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.7 Proof — Worked with */}',
  '        <section className="py-12 px-6 md:px-10 border-y border-border">',
  '          <div className="max-w-[1200px] mx-auto">',
  '            <p className="font-mono text-xs uppercase tracking-widest text-muted mb-6 text-center">Worked with</p>',
  '            <div className="flex flex-wrap justify-center gap-8 md:gap-16">',
  '              {siteConfig.clients.map((c) => <span key={c} className="text-lg md:text-xl font-bold text-muted/80">{c}</span>)}',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.8 FAQ */}',
  '        <section id="faq" className="py-20 md:py-28 px-6 md:px-10">',
  '          <div className="max-w-3xl mx-auto">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-serif font-bold mb-12">Frequently asked questions</h2>',
  '            <FAQAccordion />',
  '          </div>',
  '        </section>',
  '',
  '        {/* 8.9 Contact band */}',
  '        <section id="contact" className="py-20 md:py-28 px-6 md:px-10 bg-accent text-bg">',
  '          <div className="max-w-3xl mx-auto text-center">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-bold font-serif mb-4">Have a project in mind? Let&apos;s talk.</h2>',
  '            <p className="text-xl mb-10 opacity-90">Tell me what you need. I&apos;ll reply with the next steps.</p>',
  '            {siteConfig.availability && <div className="mb-8 inline-flex items-center gap-2 bg-bg/20 px-4 py-2 rounded-full text-sm font-medium"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-bg opacity-60" /><span className="relative inline-flex h-2 w-2 rounded-full bg-bg" /></span>{siteConfig.availability}</div>}',
  '            <div className="flex flex-col sm:flex-row gap-4 justify-center">',
  '              <a href={siteConfig.whatsappLink} target="_blank" rel="noopener noreferrer" className="bg-bg text-accent px-8 py-4 text-lg font-bold rounded-xl hover:opacity-95 transition-opacity min-h-[48px]">WhatsApp ({siteConfig.phone})</a>',
  '              <a href={"mailto:" + siteConfig.email} className="border-2 border-bg text-bg px-8 py-4 text-lg font-bold rounded-xl hover:bg-bg hover:text-accent transition-colors min-h-[48px]">Email Me</a>',
  '            </div>',
  '          </div>',
  '        </section>',
  '',
  '      </main>',
  '      <Footer />',
  '      <StickyMobileCTA />',
  '    </>',
  '  );',
  '}',
].join("\n");
fs.writeFileSync(path.join(__dirname, "src/app/page.tsx"), home);

// --- work/[slug]/page.tsx ---
const slug_dir = path.join(__dirname, "src/app/work/[slug]");
if (!fs.existsSync(slug_dir)) fs.mkdirSync(slug_dir, { recursive: true });
const work = [
  'import Link from "next/link";',
  'import type { Metadata } from "next";',
  'import { notFound } from "next/navigation";',
  'import { projects, getProjectBySlug, getRelatedProjects } from "@/content/projects";',
  'import { siteConfig } from "@/lib/config";',
  '',
  'type Props = { params: Promise<{ slug: string }> };',
  '',
  'export async function generateMetadata({ params }: Props): Promise<Metadata> {',
  '  const { slug } = await params;',
  '  const project = getProjectBySlug(slug);',
  '  if (!project) return {};',
  '  return {',
  '    title: project.title,',
  '    description: project.summary,',
  '    openGraph: {',
  '      title: project.title + " | Sangwa Jesly",',
  '      description: project.summary,',
  '      images: [{ url: project.images.cover, width: 1600, height: 1200 }],',
  '    },',
  '  };',
  '}',
  '',
  'export function generateStaticParams() {',
  '  return projects.map((p) => ({ slug: p.slug }));',
  '}',
  '',
  'export default async function ProjectPage({ params }: Props) {',
  '  const { slug } = await params;',
  '  const project = getProjectBySlug(slug);',
  '  if (!project) notFound();',
  '',
  '  const related = getRelatedProjects(project);',
  '  const idx = projects.findIndex((p) => p.slug === project.slug);',
  '  const prev = idx > 0 ? projects[idx - 1] : null;',
  '  const next = idx < projects.length - 1 ? projects[idx + 1] : null;',
  '  const crossLink = project.slug === "bongbine-brand-identity" ? "This company also has a website" : project.slug === "bongbine-website" ? "This company also has a brand identity" : null;',
  '',
  '  return (',
  '    <>',
  '      <header className="sticky top-0 z-50 bg-bg/80 backdrop-blur-md border-b border-border">',
  '        <div className="max-w-[1200px] mx-auto px-6 md:px-10 py-4 flex justify-between items-center">',
  '          <Link href="/#work" className="text-muted hover:text-fg transition-colors font-medium inline-flex items-center gap-2"><span aria-hidden="true">&larr;</span> Back to work</Link>',
  '          <a href={siteConfig.whatsappLink} target="_blank" rel="noopener noreferrer" className="bg-accent text-bg px-5 py-2.5 font-medium rounded-xl hover:opacity-90 transition-opacity">Let&apos;s talk</a>',
  '        </div>',
  '      </header>',
  '',
  '      <main id="main">',
  '        <article>',
  '          <div className="max-w-3xl mx-auto px-6 md:px-10 mt-16 md:mt-24 mb-12 text-center">',
  '            <h1 style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)" }} className="font-serif font-bold mb-6 tracking-tight">{project.title}</h1>',
  '            <p className="text-xl text-muted max-w-2xl mx-auto">{project.summary}</p>',
  '          </div>',
  '',
  '          <div className="max-w-[1200px] mx-auto px-6 md:px-10 mb-16">',
  '            <div className="aspect-video bg-surface-raised rounded-2xl overflow-hidden border border-border">',
  '              <img src={project.images.hero || project.images.cover} alt={project.title} width={2400} height={1350} className="w-full h-full object-cover" />',
  '            </div>',
  '          </div>',
  '',
  '          <div className="max-w-3xl mx-auto px-6 md:px-10 mb-16">',
  '            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 border-y border-border py-8 font-mono text-sm">',
  '              <div><div className="text-muted uppercase text-xs tracking-widest mb-1">Client</div><div className="font-medium">{project.client}</div></div>',
  '              <div><div className="text-muted uppercase text-xs tracking-widest mb-1">My role</div><div className="font-medium">{project.role}</div></div>',
  '              {project.year && <div><div className="text-muted uppercase text-xs tracking-widest mb-1">Year</div><div className="font-medium">{project.year}</div></div>}',
  '              {project.liveUrl && <div><div className="text-muted uppercase text-xs tracking-widest mb-1">Live site</div><a href={project.liveUrl} target="_blank" rel="noopener noreferrer" className="text-accent hover:underline font-medium inline-flex items-center gap-1">Visit <span aria-hidden="true">&rarr;</span></a></div>}',
  '            </div>',
  '          </div>',
  '',
  '          {project.about && <div className="max-w-[680px] mx-auto px-6 md:px-10 mb-12"><h2 className="text-2xl font-serif font-bold mb-4">About this project</h2><p className="text-muted text-lg leading-relaxed">{project.about}</p></div>}',
  '          {project.need && <div className="max-w-[680px] mx-auto px-6 md:px-10 mb-12"><h2 className="text-2xl font-serif font-bold mb-4">What they needed</h2><p className="text-muted text-lg leading-relaxed">{project.need}</p></div>}',
  '          {project.madeList && project.madeList.length > 0 && <div className="max-w-[680px] mx-auto px-6 md:px-10 mb-12"><h2 className="text-2xl font-serif font-bold mb-4">What I made</h2><ul className="list-disc list-inside text-muted text-lg leading-relaxed space-y-2">{project.madeList.map((item, i) => <li key={i}>{item}</li>)}</ul></div>}',
  '          {project.result && <div className="max-w-[680px] mx-auto px-6 md:px-10 mb-16"><h2 className="text-2xl font-serif font-bold mb-4">The result</h2><p className="text-muted text-lg leading-relaxed">{project.result}</p></div>}',
  '',
  '          {project.images.gallery.length > 0 && (',
  '            <div className="max-w-[1200px] mx-auto px-6 md:px-10 mb-20">',
  '              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">',
  '                {project.images.gallery.map((img, i) => (',
  '                  <div key={i} className={"rounded-2xl overflow-hidden border border-border bg-surface-raised" + (i % 3 === 0 ? " md:col-span-2" : "")}>',
  '                    <img src={img.src} alt={img.alt} width={1600} height={1000} loading="lazy" className="w-full h-full object-cover" />',
  '                    {img.caption && <p className="px-4 py-3 text-sm text-muted">{img.caption}</p>}',
  '                  </div>',
  '                ))}',
  '              </div>',
  '            </div>',
  '          )}',
  '',
  '          <div className="max-w-3xl mx-auto px-6 md:px-10 mb-20">',
  '            <h2 className="text-2xl font-serif font-bold mb-8">More projects</h2>',
  '            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">',
  '              {prev && <Link href={"/work/" + prev.slug} className="group border border-border rounded-2xl p-6 hover:border-accent/40 transition-colors"><p className="font-mono text-xs text-muted uppercase tracking-widest mb-2">&larr; Previous</p><p className="font-bold font-serif">{prev.title}</p></Link>}',
  '              {next && <Link href={"/work/" + next.slug} className="group border border-border rounded-2xl p-6 hover:border-accent/40 transition-colors text-right"><p className="font-mono text-xs text-muted uppercase tracking-widest mb-2">Next &rarr;</p><p className="font-bold font-serif">{next.title}</p></Link>}',
  '            </div>',
  '            {related.length > 0 && <div className="mt-6 flex flex-col gap-3">{related.map((r) => <Link key={r.slug} href={"/work/" + r.slug} className="text-accent hover:underline font-medium inline-flex items-center gap-2">{crossLink || "Related: " + r.title} <span aria-hidden="true">&rarr;</span></Link>)}</div>}',
  '          </div>',
  '        </article>',
  '',
  '        <section className="py-20 md:py-28 px-6 md:px-10 bg-accent text-bg">',
  '          <div className="max-w-3xl mx-auto text-center">',
  '            <h2 style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)" }} className="font-bold font-serif mb-4">Want something like this for your business? Let&apos;s talk.</h2>',
  '            <div className="flex flex-col sm:flex-row justify-center gap-4 mt-8">',
  '              <a href={siteConfig.whatsappLink} target="_blank" rel="noopener noreferrer" className="bg-bg text-accent px-8 py-4 text-lg font-bold rounded-xl hover:opacity-95 transition-opacity min-h-[48px]">WhatsApp</a>',
  '              <a href={"mailto:" + siteConfig.email} className="border-2 border-bg text-bg px-8 py-4 text-lg font-bold rounded-xl hover:bg-bg hover:text-accent transition-colors min-h-[48px]">Email</a>',
  '            </div>',
  '          </div>',
  '        </section>',
  '      </main>',
  '    </>',
  '  );',
  '}',
].join("\n");
fs.writeFileSync(path.join(slug_dir, "page.tsx"), work);

// --- not-found.tsx ---
const nf = [
  'import Link from "next/link";',
  'import { siteConfig } from "@/lib/config";',
  '',
  'export default function NotFound() {',
  '  return (',
  '    <div className="min-h-screen flex flex-col items-center justify-center px-6 text-center">',
  '      <p className="font-mono text-accent text-sm uppercase tracking-widest mb-4">404</p>',
  '      <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4">Page not found</h1>',
  '      <p className="text-muted text-lg mb-8 max-w-md">Sorry, I couldn&apos;t find that page. It may have moved or no longer exists.</p>',
  '      <div className="flex flex-col sm:flex-row gap-4">',
  '        <Link href="/" className="bg-accent text-bg px-8 py-4 font-bold rounded-xl hover:opacity-90 transition-opacity">Go home</Link>',
  '        <a href={siteConfig.whatsappLink} target="_blank" rel="noopener noreferrer" className="border border-border text-fg px-8 py-4 font-bold rounded-xl hover:bg-surface transition-colors">Contact me</a>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
].join("\n");
fs.writeFileSync(path.join(__dirname, "src/app/not-found.tsx"), nf);

// --- sitemap.ts ---
const sitemap = [
  'import type { MetadataRoute } from "next";',
  'import { projects } from "@/content/projects";',
  '',
  'export default function sitemap(): MetadataRoute.Sitemap {',
  '  const base = "https://sangwajesly.vercel.app";',
  '  return [',
  '    { url: base, lastModified: new Date(), priority: 1 },',
  '    ...projects.map((p) => ({ url: base + "/work/" + p.slug, lastModified: new Date() })),',
  '  ];',
  '}',
].join("\n");
fs.writeFileSync(path.join(__dirname, "src/app/sitemap.ts"), sitemap);

// --- robots.txt ---
const pubDir = path.join(__dirname, "public");
if (!fs.existsSync(pubDir)) fs.mkdirSync(pubDir, { recursive: true });
fs.writeFileSync(path.join(pubDir, "robots.txt"), "User-agent: *\nAllow: /\n\nSitemap: https://sangwajesly.vercel.app/sitemap.xml\n");

// --- Create placeholder dirs ---
const slugs = ["bongbine-brand-identity","nervtek-community-launch","drone-up-cameroon","bongbine-website","klarify-website","civilsalt-learning-platform","traitz-tech-social-media","business-flyers"];
slugs.forEach((s) => {
  const d = path.join(pubDir, "work", s);
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
});
["brand","clients"].forEach((d) => {
  const p2 = path.join(pubDir, d);
  if (!fs.existsSync(p2)) fs.mkdirSync(p2, { recursive: true });
});

console.log("All files generated successfully.");
